### ISSUE TITLE
Godaddy Server(Shared Hosting) connecting to AWS iot core showing error.

### ISSUE THREAD

**Issue by ajay26kumar** [php-mqtt/laravel-client#27]
PhpMqtt\Client\Exceptions\ConnectingToBrokerFailedException
[1000] Establishing a connection to the MQTT broker failed: Socket error [101]: Network is unreachable

When I am trying to connect to AWS IoT core through Godaddy Server(Shared Hosting) above error is showing but when i am connecting through locally it's working fine.

Please help in this. Thanks in advance

**Comment by Namoshek** [comment]
If you are able to establish a connection locally but not within your GoDaddy hosting, it probably means that the webserver is blocking the outgoing traffic. This is most likely because ports 1883 and 8883 are quite uncommon to be used within a web app hosted on shared hosting.

Since I'm not familiar with this type of hosting, I cannot really help you with this though. I guess your best chances are contacting the GoDaddy support regarding outgoing connections to AWS on the relevant ports and whether there is a way you can allow such traffic.
