### ISSUE TITLE
Can this be used to make a MQTT sink?

### ISSUE THREAD

**Issue by Frtrillo** [php-mqtt/laravel-client#29]
Hello, first thanks for the library and work.
Now, I have a question: Can we use this library to make a MQTT sink to store ALL the MQTT messages(which are going to be **_a lot!_**) onto the database (like with the usual, eloquent new() and model->save(); helpers when storing information)? 
Like this example: https://github.com/php-mqtt/client-examples/blob/master/04_hooks/03_use_a_message_received_event_handler_to_log_received_messages.php but storing on the database.
Or its just too much for PHP and better do it with othe technologies like kafka or some script in NodeJS/Python.

**Comment by Namoshek** [comment]
Yes, every MQTT client can be used to build an MQTT sink. Even `mosquitto_sub` can be used to create a file-based sink. But, of course, this doesn't mean it is a good idea to do so. 😄 

Ultimately, your limiting factor will be the database. You can optimize tihs part by inserting records in chunks (i.e. collecting `n` published messages and insert the whole bulk at once to safe round-trips to the database). Furthermore you can make the inserts more efficient by skipping Eloquent all together and use `DB::table('mqtt_sink')->insert([...])` instead. For the best performance, the table should not have any indexes.
But in the end, if your database cannot keep up with the load or if you start to query the table during inserts, you will run into issues. I guess the insert performance can be scaled vertically, but query performance is hard to deal with. Maybe partitioning the data could help by allowing reads only on older data.

Most brokers allow to directly connect some kind of sink though. This solution is always more important than implementing custom logic in a third application. A direct connection also removes the need for redundancy on the client-side via shared subscriptions, because the broker itself will send the data to the sink. Furthermore, if you implemented a sink in PHP and your subscribed _sink clients_ cannot not keep up with the amount of messages to process, their delivery queue on the broker runs full and messages will be dropped. I guess this is something which is easier to handle with a directly connected sink.

This is an interesting question though. Thanks for asking!
