### ISSUE TITLE
Enhancement Proposal: Addition of interrupt and subscribe methods to MQTT Facade and ConnectionManager Class 

### ISSUE THREAD

**Issue by StevenFV** [php-mqtt/laravel-client#54]
Hello,  

I hope this message finds you well. I am currently using your php-mqtt/laravel-client library in one of my projects and I find it extremely useful. However, I have noticed that the MQTT facade and ConnectionManager class could benefit from the addition of interrupt and subscribe methods.  

The interrupt method would be useful to exit the loop during the next iteration, which can be particularly handy in certain use cases. The subscribe method, on the other hand, would allow subscribing to topics, which is a common requirement in MQTT applications.  

Here is a idea of what the methods could look like with addition the README update:

### MQTT.php:
```php
namespace PhpMqtt\Client\Facades;

use Illuminate\Support\Facades\Facade;
use PhpMqtt\Client\ConnectionManager;
use PhpMqtt\Client\Contracts\MqttClient;

/**
 * @method static MqttClient connection(string $name = null)
 * @method static void interrupt(string $connection = null) // add interrupt to MQTT Facade
 * @method static void disconnect(string $connection = null)
 * @method static void publish(string $topic, string $message, bool $retain = false, string $connection = null)
 * @method static void subscribe(string $topic, callable $message, int $qos = 0, string $connection = null) // add subscribe to MQTT Facade
 // ...
``` 

### ConnectionManager.php
```php
/**
     * Interrupts the given connection if opened.
     *
     * @param string|null $connection
     */
    public function interrupt(string $connection = null): void
    {
        if ($connection === null) {
            $connection = $this->defaultConnection;
        }

        if (array_key_exists($connection, $this->connections)) {
            $this->connections[$connection]->interrupt();
        }
    }

/**
     * Subscribes to the given topic on the given connection.
     *
     * @param string $topic
     * @param callable $message
     * @param int $qos
     * @param string|null $connection
     * @throws BindingResolutionException
     * @throws ConfigurationInvalidException
     * @throws ConnectingToBrokerFailedException
     * @throws ConnectionNotAvailableException
     * @throws DataTransferException
     * @throws ProtocolNotSupportedException
     * @throws RepositoryException
     */
    public function subscribe(string $topic, callable $message, int $qos = 0, string $connection = null): void
    {
        $client = $this->connection($connection);

        $client->subscribe($topic, $message, $qos);
    }
// ...
```

### README.md
In order to escape the loop, you can also call `MQTT::interrupt()` which will exit the loop during
the next iteration. The method can, for example, be called in a registered signal handler:
```php
/** @var \PhpMqtt\Client\Contracts\MqttClient $mqtt */
pcntl_signal(SIGINT, function () use ($mqtt) {
    MQTT::interrupt();
});
```

Very similar to publishing with QoS level 1 and 2, subscribing requires to run an event loop.
Although before running the loop, topics need to be subscribed to:

```php
use PhpMqtt\Client\Facades\MQTT;

MQTT::subscribe('some/topic', function (string $topic, string $message) {
    echo sprintf('Received QoS level 1 message on topic [%s]: %s', $topic, $message);
}, 1);
MQTT::connection()->loop(true);
```

If you agree with these changes, I would be more than happy to contribute and push my changes via a pull request. Please let me know if you would like me to proceed with this.  

Best regards, StevenFV

**Comment by Namoshek** [comment]
Thank you for suggesting this change. However, there is a reason why these methods are not part of the facade:

- The `interrupt()` method is supposed to be called from _within_ the loop. That's actually only possible from within subscription callbacks and event handler callbacks, although the latter makes inherently more sense in most cases. Since this callback already receives a reference to the `MqttClient` as parameter, that one should be used instead.

- The `subscribe()` method on the other hand requires to be followed by `loop()` in order to work, since the client has to listen for messages by the broker (infinitely by default). Since the `MQTT` facade supports more than just one connection though, it makes more sense to retrieve an instance of the client and call both methods on that. This would also be the preferred solution for `interrupt()` within subscriptions:
    ```php
    $client = MQTT::connection();
    $client->registerLoopEventHandler(function (MqttClient $mqtt, float $elapsedTime) use ($logger) {
        if ($elapsedTime > 5) {
            $mqtt->interrupt(); // use the provided reference where possible
        }
    });
    $client->subscribe('some/topic/+', function (string $topic, string $message) use ($client) {
        $this->processMessage($topic, $message);
        $client->interrupt(); // fall back to the client passed as reference to the callback when subscribing
    });
    $client->loop();
    ```

I see how it may be tempting to use facades as much as possible. I have to say though that it is actually bad practice due to strong coupling and intransparent use of dependencies. When you pass services and classes via dependency injection in the constructor, you can see during instantiation of a class what the class uses. When you use facades, you really have to look at the implementation to understand the dependencies. That's why you should not overuse them (in my opinion). The best approach to using this library is injecting the `ConnectionManager` where needed. It provides the same functionality as the `MQTT` facade.

**Comment by StevenFV** [comment]
Ok, thank you for your answer, I'll take good note of it.
